language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

script:
  - composer install
  - vendor/bin/phpcs --standard=PSR2 bin src example tests *.php
  - vendor/bin/phpunit tests

branches:
  only:
    - master
